import { describe, expect, it, vi, beforeEach } from 'vitest';
import {
  buildOfferDocumentFileName,
  createOfferDocument,
  downloadOfferDocument,
} from '../offerDocument.js';

const mockSave = vi.fn();
const mockSetFont = vi.fn();
const mockSetFontSize = vi.fn();
const mockText = vi.fn();
const mockSplitTextToSize = vi.fn((text) => [text]);

vi.mock('jspdf', () => ({
  jsPDF: vi.fn(() => ({
    save: mockSave,
    setFont: mockSetFont,
    setFontSize: mockSetFontSize,
    text: mockText,
    splitTextToSize: mockSplitTextToSize,
  })),
}));

const application = {
  job: { title: 'Senior Data Analyst' },
  organization: { name: 'Cynectex' },
  candidate: { fullName: 'Aki Yapa' },
  offer: {
    title: 'Senior Data Analyst Offer',
    compensationAmount: 450000,
    compensationCurrency: 'LKR',
    compensationPeriod: 'MONTHLY',
    startDate: '2026-04-01T00:00:00.000Z',
    expiresAt: '2026-04-15T12:00:00.000Z',
    note: 'Arrive on site at 9:00 AM.',
    status: 'PENDING',
  },
  offerHistory: [
    {
      id: 'history-1',
      eventType: 'SENT',
      createdAt: '2026-03-10T09:00:00.000Z',
      note: 'Offer shared with the candidate.',
      offer: {
        title: 'Senior Data Analyst Offer',
        compensationAmount: 450000,
        compensationCurrency: 'LKR',
        compensationPeriod: 'MONTHLY',
      },
    },
  ],
};

describe('offerDocument', () => {
  beforeEach(() => {
    mockSave.mockReset();
    mockSetFont.mockReset();
    mockSetFontSize.mockReset();
    mockText.mockReset();
    mockSplitTextToSize.mockReset();
    mockSplitTextToSize.mockImplementation((text) => [text]);
  });

  it('builds a stable PDF file name', () => {
    expect(buildOfferDocumentFileName(application)).toBe('cynectex-senior-data-analyst-offer-offer.pdf');
  });

  it('creates the offer document with company and role details', () => {
    createOfferDocument(application, { generatedFor: 'candidate' });

    expect(mockText).toHaveBeenCalledWith('Employment Offer', 48, 68);
    expect(mockText).toHaveBeenCalledWith('Generated by InterviewAI Pro', 48, 800);
  });

  it('downloads the generated offer PDF', () => {
    const fileName = downloadOfferDocument(application, { generatedFor: 'company' });

    expect(fileName).toBe('cynectex-senior-data-analyst-offer-offer.pdf');
    expect(mockSave).toHaveBeenCalledWith('cynectex-senior-data-analyst-offer-offer.pdf');
  });
});
