import { jsPDF } from 'jspdf';
import {
  formatOfferCompensation,
  formatOfferHistoryEventLabel,
} from './applicationOfferPresentation.js';

const formatDate = (value, { showTime = false } = {}) => {
  if (!value) return 'N/A';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return 'N/A';
  return date.toLocaleString(undefined, showTime
    ? { dateStyle: 'medium', timeStyle: 'short' }
    : { dateStyle: 'medium' });
};

const slugify = (value) =>
  String(value || 'offer')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    || 'offer';

export const buildOfferDocumentFileName = (application = {}) => {
  const companyName = application?.organization?.name || 'company';
  const roleTitle = application?.offer?.title || application?.job?.title || 'offer';
  return `${slugify(companyName)}-${slugify(roleTitle)}-offer.pdf`;
};

export const createOfferDocument = (
  application,
  { generatedFor = 'candidate', docFactory = () => new jsPDF({ unit: 'pt', format: 'a4' }) } = {},
) => {
  const doc = docFactory();
  const offer = application?.offer || {};
  const history = Array.isArray(application?.offerHistory) ? application.offerHistory : [];
  const companyName = application?.organization?.name || 'Company';
  const roleTitle = offer.title || application?.job?.title || 'Offer';
  const candidateName = application?.candidate?.fullName || application?.candidate?.name || 'Candidate';
  const compensation = formatOfferCompensation(offer) || 'Compensation unavailable';

  let cursorY = 48;
  const left = 48;
  const line = (text, options = {}) => {
    doc.setFont(options.bold ? 'helvetica' : 'helvetica', options.bold ? 'bold' : 'normal');
    doc.setFontSize(options.size || 11);
    doc.text(String(text || ''), left, cursorY);
    cursorY += options.gap || 18;
  };
  const block = (label, value) => {
    line(label, { bold: true, size: 10, gap: 14 });
    const lines = doc.splitTextToSize(String(value || 'N/A'), 500);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.text(lines, left, cursorY);
    cursorY += (Array.isArray(lines) ? lines.length : 1) * 14 + 10;
  };

  line('InterviewAI Pro', { bold: true, size: 12, gap: 20 });
  line('Employment Offer', { bold: true, size: 22, gap: 24 });
  line(`${companyName} - ${roleTitle}`, { size: 13, gap: 24 });

  block('Candidate', candidateName);
  block('Generated For', generatedFor === 'company' ? 'Hiring Team Copy' : 'Candidate Copy');
  block('Company', companyName);
  block('Role', roleTitle);
  block('Compensation', compensation);
  block('Start Date', formatDate(offer.startDate));
  block('Offer Expiry', formatDate(offer.expiresAt, { showTime: true }));
  block('Offer Status', offer.status || application?.status || 'PENDING');
  if (offer.note) {
    block('Offer Note', offer.note);
  }

  if (offer.acceptedAt) {
    block('Accepted At', formatDate(offer.acceptedAt, { showTime: true }));
  }
  if (offer.declinedAt) {
    block('Declined At', formatDate(offer.declinedAt, { showTime: true }));
  }
  if (offer.declineReason) {
    block('Decline Reason', offer.declineReason);
  }

  if (history.length > 0) {
    line('Offer Timeline', { bold: true, size: 14, gap: 18 });
    history.slice(0, 5).forEach((entry) => {
      const summary = [
        formatOfferHistoryEventLabel(entry.eventType),
        formatDate(entry.createdAt, { showTime: true }),
        entry.note || null,
      ].filter(Boolean).join(' - ');
      const lines = doc.splitTextToSize(summary, 500);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.text(lines, left, cursorY);
      cursorY += (Array.isArray(lines) ? lines.length : 1) * 13 + 8;
    });
  }

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Generated by InterviewAI Pro', left, 800);
  return doc;
};

export const downloadOfferDocument = (application, options = {}) => {
  const doc = createOfferDocument(application, options);
  const fileName = buildOfferDocumentFileName(application);
  doc.save(fileName);
  return fileName;
};
